---
- name: Install redhat-lsb
  sudo: yes
  register: result_redhat_lsb
  until: result_redhat_lsb|success
  yum:
    name: redhat-lsb
    state: present

- name: Reread ansible_lsb facts
  setup: filter=ansible_lsb*

- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  sudo: yes
  register: result_epel_release
  until: result_epel_release|success
  yum:
    name: epel-release
    state: present
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists
